// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2VxPP_9aJb3m4OtU6bEauqtsTQZjhTIU',
    appId: '1:900347995433:web:a6fd520b9c0ef0b3050338',
    messagingSenderId: '900347995433',
    projectId: 'mechtrack-f673d',
    authDomain: 'mechtrack-f673d.firebaseapp.com',
    storageBucket: 'mechtrack-f673d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw49DWNu_C9XwdNvH-vyMbTJgXTFz9kVY',
    appId: '1:900347995433:android:9439a7089222ceea050338',
    messagingSenderId: '900347995433',
    projectId: 'mechtrack-f673d',
    storageBucket: 'mechtrack-f673d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0FOhB-Ux_ikPYi81f-kitYFG_lQnT_GM',
    appId: '1:900347995433:ios:af35515644268806050338',
    messagingSenderId: '900347995433',
    projectId: 'mechtrack-f673d',
    storageBucket: 'mechtrack-f673d.firebasestorage.app',
    iosBundleId: 'com.example.mechTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0FOhB-Ux_ikPYi81f-kitYFG_lQnT_GM',
    appId: '1:900347995433:ios:af35515644268806050338',
    messagingSenderId: '900347995433',
    projectId: 'mechtrack-f673d',
    storageBucket: 'mechtrack-f673d.firebasestorage.app',
    iosBundleId: 'com.example.mechTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2VxPP_9aJb3m4OtU6bEauqtsTQZjhTIU',
    appId: '1:900347995433:web:9f416a091ad48e42050338',
    messagingSenderId: '900347995433',
    projectId: 'mechtrack-f673d',
    authDomain: 'mechtrack-f673d.firebaseapp.com',
    storageBucket: 'mechtrack-f673d.firebasestorage.app',
  );
}
